// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package persistence

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateAnalyticsEvent(ctx context.Context, arg CreateAnalyticsEventParams) (AnalyticsEvent, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreatePaymentRetryJob(ctx context.Context, arg CreatePaymentRetryJobParams) (PaymentRetryJob, error)
	CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error)
	CreatePaymentWebhook(ctx context.Context, arg CreatePaymentWebhookParams) (PaymentWebhook, error)
	CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteMenuItem(ctx context.Context, id uuid.UUID) error
	DeleteRestaurant(ctx context.Context, arg DeleteRestaurantParams) error
	DeleteStaff(ctx context.Context, arg DeleteStaffParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAdminDashboardStats(ctx context.Context) (GetAdminDashboardStatsRow, error)
	GetAllAdminEmails(ctx context.Context) ([]string, error)
	GetAnalyticsAggregates(ctx context.Context, arg GetAnalyticsAggregatesParams) ([]AnalyticsAggregate, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetMenuItemByID(ctx context.Context, id uuid.UUID) (MenuItem, error)
	GetPaymentTransactionByTxRef(ctx context.Context, txRef string) (PaymentTransaction, error)
	GetRecentAdminLogs(ctx context.Context, limit int32) ([]GetRecentAdminLogsRow, error)
	GetRestaurantByID(ctx context.Context, id uuid.UUID) (Restaurant, error)
	GetRestaurantBySlug(ctx context.Context, slug string) (Restaurant, error)
	GetRestaurantDetailsForAdmin(ctx context.Context, id uuid.UUID) (GetRestaurantDetailsForAdminRow, error)
	GetActiveSubscriptionByOwner(ctx context.Context, ownerID uuid.UUID) (GetActiveSubscriptionByOwnerRow, error)
	GetLatestSubscriptionByOwner(ctx context.Context, ownerID uuid.UUID) (GetLatestSubscriptionByOwnerRow, error)
	UpdateOldSubscriptionsStatus(ctx context.Context, arg UpdateOldSubscriptionsStatusParams) error
	GetSubscriptionPlanBySlug(ctx context.Context, slug string) (SubscriptionPlan, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	IncrementMenuItemViewCount(ctx context.Context, id uuid.UUID) error
	IncrementRestaurantViewCount(ctx context.Context, id uuid.UUID) error
	ListActivityLogsByRestaurant(ctx context.Context, arg ListActivityLogsByRestaurantParams) ([]ListActivityLogsByRestaurantRow, error)
	ListActivityLogsWithFilters(ctx context.Context, arg ListActivityLogsWithFiltersParams) ([]ListActivityLogsWithFiltersRow, error)
	ListAnalyticsEventsWithFilters(ctx context.Context, arg ListAnalyticsEventsWithFiltersParams) ([]AnalyticsEvent, error)
	ListCategoriesByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]Category, error)
	ListInvoicesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Invoice, error)
	ListInvoicesWithFilters(ctx context.Context, arg ListInvoicesWithFiltersParams) ([]Invoice, error)
	ListMenuItemsByCategory(ctx context.Context, categoryID uuid.UUID) ([]MenuItem, error)
	ListMenuItemsByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]MenuItem, error)
	ListRestaurantsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Restaurant, error)
	ListRestaurantsWithFilters(ctx context.Context, arg ListRestaurantsWithFiltersParams) ([]Restaurant, error)
	ListStaffByOwner(ctx context.Context, ownerID *uuid.UUID) ([]User, error)
	ListStaffByRestaurant(ctx context.Context, restaurantID *uuid.UUID) ([]User, error)
	ListSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersWithFilters(ctx context.Context, arg ListUsersWithFiltersParams) ([]User, error)
	MarkWebhookAsProcessed(ctx context.Context, providerEventID pgtype.Text) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdatePaymentRetryJob(ctx context.Context, arg UpdatePaymentRetryJobParams) (PaymentRetryJob, error)
	UpdatePaymentTransactionStatus(ctx context.Context, arg UpdatePaymentTransactionStatusParams) (PaymentTransaction, error)
	UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) (Restaurant, error)
	// UpdateRestaurantStatus(ctx context.Context, arg UpdateRestaurantStatusParams) (Restaurant, error)
	UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) error
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertAnalyticsAggregate(ctx context.Context, arg UpsertAnalyticsAggregateParams) (AnalyticsAggregate, error)
}

var _ Querier = (*Queries)(nil)
